# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-12 01:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommonInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('commoninfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inheritance.CommonInfo')),
                ('home_group', models.CharField(max_length=5)),
            ],
            bases=('inheritance.commoninfo',),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('commoninfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inheritance.CommonInfo')),
                ('subject', models.CharField(max_length=30)),
            ],
            bases=('inheritance.commoninfo',),
        ),
    ]
