# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0003_auto_20171010_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
