# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-11 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0007_auto_20171011_1054'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('friends', models.ManyToManyField(blank=True, related_name='_facebookuser_friends_+', to='doc.FacebookUser')),
            ],
        ),
        migrations.CreateModel(
            name='InstagramUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('following', models.ManyToManyField(blank=True, to='doc.InstagramUser')),
            ],
        ),
        migrations.RemoveField(
            model_name='twitteruser',
            name='friends',
        ),
        migrations.AlterField(
            model_name='pizza',
            name='toppings',
            field=models.ManyToManyField(blank=True, to='doc.Topping'),
        ),
        migrations.DeleteModel(
            name='TwitterUser',
        ),
    ]
