# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-11 20:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0009_auto_20171011_2250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membership',
            old_name='Group',
            new_name='group',
        ),
        migrations.AddField(
            model_name='membership',
            name='recommender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommend_membership_set', to='doc.Idol'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='idol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_set', to='doc.Idol'),
        ),
    ]
