# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-12 01:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0012_auto_20171012_0652'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'verbose_name': '장소 목록'},
        ),
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
